name: Integration Tests

on:
  push:
    branches:
      - main # Or your primary branch name
  pull_request:
    branches:
      - main # Or your primary branch name
  workflow_dispatch: # Retain manual triggering

env:
  SIMULATOR_NUM_MESSAGES_CI: "1000000" # Number of messages for CI tests
  DOTNET_REDIS_URL: "localhost:6379"
  DOTNET_KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"

jobs:
  run-integration-tests:
    name: Run Flink.NET Integration Tests
    runs-on: windows-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure Docker is running
        run: |
          if (-not (Get-Service -Name com.docker.service -ErrorAction SilentlyContinue)) {
            choco install docker-desktop --pre -y
          }
          Start-Service com.docker.service
          docker info

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET Aspire Workload
        run: dotnet workload install aspire

      - name: Restore .NET Workloads for Solutions
        run: |
          dotnet workload restore FlinkDotNet/FlinkDotNet.sln
          dotnet workload restore FlinkDotNetAspire/FlinkDotNetAspire.sln
          dotnet workload restore FlinkDotNet.WebUI/FlinkDotNet.WebUI.sln

      - name: Build Solution (including Verifier)
        run: |
          echo "Building FlinkDotNetAspire solution..."
          Push-Location FlinkDotNetAspire
          dotnet build FlinkDotNetAspire.sln --configuration Release
          Pop-Location

      - name: Start .NET Aspire Application
        run: |
          Write-Host "Starting Aspire AppHost with SIMULATOR_NUM_MESSAGES_CI=${env:SIMULATOR_NUM_MESSAGES_CI}..."
          Push-Location FlinkDotNetAspire/FlinkDotNetAspire.AppHost

          Write-Host "Generating Aspire manifest..."
          dotnet publish FlinkDotNetAspire.AppHost.csproj --configuration Release -p:IsPublishable=true -p:AspireManifestPublishOutputPath=../publish -t:GenerateAspireManifest
          Copy-Item ../publish/manifest.json ../aspire-manifest.json -Force
          Write-Host "Aspire manifest generated at ../aspire-manifest.json"

          $env:SIMULATOR_NUM_MESSAGES = "${{ env.SIMULATOR_NUM_MESSAGES_CI }}"
          $env:ASPIRE_ALLOW_UNSECURED_TRANSPORT = "true"
          $env:ASPNETCORE_URLS = "http://localhost:5199"
          $env:DOTNET_DASHBOARD_OTLP_ENDPOINT_URL = "http://localhost:4317"

          $process = Start-Process -FilePath dotnet -ArgumentList "run --project FlinkDotNetAspire.AppHost.csproj --no-launch-profile --no-build -c Release" -RedirectStandardOutput ../../aspire-apphost.log -RedirectStandardError ../../aspire-apphost.err.log -PassThru
          $process.Id | Out-File ../../aspire-apphost.pid -Encoding ASCII
          Pop-Location
          Write-Host "Aspire AppHost started with PID $($process.Id)"
          Write-Host "Waiting for Aspire AppHost to initialize..."
          Start-Sleep -Seconds 30


      # The AppHost binds Redis and Kafka to default ports. The environment
      # variables above provide the localhost connection strings for the tests.
      - name: Health Check Loop
        env:
          DOTNET_ENVIRONMENT: "Development" # Helps Aspire resolve services if it has multiple modes
          DOTNET_REDIS_URL: localhost:6379
          DOTNET_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
        run: |
          $maxAttempts = 10
          $delaySeconds = 15
          $verifierDll = "./FlinkDotNetAspire/IntegrationTestVerifier/bin/Release/net8.0/FlinkDotNet.IntegrationTestVerifier.dll"

          for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
            echo "Health check attempt $attempt/$maxAttempts..."
            & dotnet $verifierDll --health-check
            if ($LASTEXITCODE -eq 0) {
              echo "Health check PASSED."
              break
            }
            echo "Health check FAILED. Waiting $delaySeconds seconds before retry..."
            Start-Sleep -Seconds $delaySeconds
            if ($attempt -eq $maxAttempts) {
              echo "Max health check attempts reached. Failing workflow."
              exit 1
            }
          }

      - name: Run Verification Tests
        env:
          # SIMULATOR_NUM_MESSAGES needs to be the same as used by the job simulator.
          SIMULATOR_NUM_MESSAGES: ${{ env.SIMULATOR_NUM_MESSAGES_CI }}
          DOTNET_ENVIRONMENT: "Development"
          DOTNET_REDIS_URL: localhost:6379
          DOTNET_KAFKA_BOOTSTRAP_SERVERS: localhost:9092
        run: |
          echo "Running verification tests with SIMULATOR_NUM_MESSAGES=${{ env.SIMULATOR_NUM_MESSAGES_CI }}..."
          Write-Host "DOTNET_REDIS_URL from env: $env:DOTNET_REDIS_URL"
          Write-Host "DOTNET_KAFKA_BOOTSTRAP_SERVERS from env: $env:DOTNET_KAFKA_BOOTSTRAP_SERVERS"
          $verifierDll = "./FlinkDotNetAspire/IntegrationTestVerifier/bin/Release/net8.0/FlinkDotNet.IntegrationTestVerifier.dll"
          & dotnet $verifierDll
          if ($LASTEXITCODE -ne 0) {
            echo "Verification tests FAILED."
            exit 1
          }
          echo "Verification tests PASSED."

      - name: Stop .NET Aspire Application (Best Effort)
        if: always()
        run: |
          Write-Host "Attempting to stop .NET Aspire AppHost..."
          if (Test-Path "aspire-apphost.pid") {
            $pid = Get-Content "aspire-apphost.pid"
            Stop-Process -Id $pid -Force -ErrorAction SilentlyContinue
          }
          Get-Process | Where-Object { $_.Path -like '*FlinkDotNetAspire.AppHost*' } | Stop-Process -Force -ErrorAction SilentlyContinue
          Write-Host "Cleanup complete."
