name: Integration Tests

on:
  push:
    branches:
      - main
  pull_request:
    types: [synchronize]
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: |
    ${{ github.workflow }}-${{ github.workflow_ref }}-${{
      github.event_name == 'pull_request' 
      && github.event.pull_request.number 
      || github.ref_name }}
  cancel-in-progress: true

env:
  ASPIRE_ALLOW_UNSECURED_TRANSPORT: "true"

jobs:
  run-integration-tests:
    name: Run Flink.NET Aspire Integration Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure Docker is running
        run: docker info

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET Aspire Workload
        run: dotnet workload install aspire

      - name: Restore .NET Workloads for Solutions
        run: |
          dotnet workload restore FlinkDotNet/FlinkDotNet.sln
          dotnet workload restore FlinkDotNetAspire/FlinkDotNetAspire.sln

      - name: Build Solutions
        run: |
          echo "Building FlinkDotNet solution (dependency)..."
          dotnet build FlinkDotNet/FlinkDotNet.sln --configuration Release
          
          echo "Building FlinkDotNetAspire solution (including integration tests)..."
          dotnet build FlinkDotNetAspire/FlinkDotNetAspire.sln --configuration Release

      - name: Run Integration Tests
        run: |
          echo "Running Aspire integration tests..."
          dotnet test FlinkDotNetAspire/FlinkDotNetAspire.IntegrationTests/FlinkDotNetAspire.IntegrationTests.csproj --configuration Release --logger trx --collect:"XPlat Code Coverage"

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: integration-test-results
          path: |
            **/*.trx
            **/*.coverage