name: Integration Tests

on:
  push:
    branches:
      - main # Or your primary branch name
  pull_request:
    branches:
      - main # Or your primary branch name
  workflow_dispatch: # Retain manual triggering

env:
  SIMULATOR_NUM_MESSAGES_CI: "1000000" # Number of messages for CI tests

jobs:
  run-integration-tests:
    name: Run Flink.NET Integration Tests
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: pwsh

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Verify Docker is available
        run: docker version

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Install .NET Aspire Workload
        run: dotnet workload install aspire

      - name: Restore .NET Workloads for Solutions
        run: |
          dotnet workload restore FlinkDotNet/FlinkDotNet.sln
          dotnet workload restore FlinkDotNetAspire/FlinkDotNetAspire.sln
          dotnet workload restore FlinkDotNet.WebUI/FlinkDotNet.WebUI.sln

      - name: Build Solution (including Verifier)
        run: |
          echo "Building FlinkDotNetAspire solution..."
          Push-Location FlinkDotNetAspire
          dotnet build FlinkDotNetAspire.sln --configuration Release
          Pop-Location

      - name: Start .NET Aspire Application
        run: |
          echo "Starting Aspire AppHost with SIMULATOR_NUM_MESSAGES_CI=${{ env.SIMULATOR_NUM_MESSAGES_CI }}..."
          Push-Location FlinkDotNetAspire/FlinkDotNetAspire.AppHost

          echo "Generating Aspire manifest..."
          dotnet publish FlinkDotNetAspire.AppHost.csproj --configuration Release -p:IsPublishable=true -p:AspireManifestPublishOutputPath=../publish -t:GenerateAspireManifest
          Copy-Item ../publish/manifest.json ../aspire-manifest.json
          Write-Host "Aspire manifest generated at ../aspire-manifest.json"

          # Start Aspire in the background. Pass SIMULATOR_NUM_MESSAGES to the environment of the process
          # Aspire AppHost will propagate this to the flinkjobsimulator if it's configured to read it.
          # Note: For Start-Process, environment variables are typically inherited or need specific setup.
          # A robust way is to ensure FlinkJobSimulator/Program.cs reads this variable.
          # For now, relying on inheritance or existing AppHost logic to pick up SIMULATOR_NUM_MESSAGES.
          # If FlinkJobSimulator's Program.cs is not reading it, it will use its internal default.
          # This might require a change in FlinkJobSimulator's Program.cs to respect SIMULATOR_NUM_MESSAGES.
          $env:SIMULATOR_NUM_MESSAGES = $env:SIMULATOR_NUM_MESSAGES_CI
          Write-Host "Environment SIMULATOR_NUM_MESSAGES set to $env:SIMULATOR_NUM_MESSAGES for Aspire AppHost process"

          # Allow Aspire to serve HTTP endpoints and the dashboard over HTTP
          $env:ASPIRE_ALLOW_UNSECURED_TRANSPORT = "true"
          $env:ASPNETCORE_URLS = "http://localhost:5199"
          $env:DOTNET_DASHBOARD_OTLP_ENDPOINT_URL = "http://localhost:4317"

          $aspireLog = "../../aspire-apphost.log"
          $process = Start-Process -FilePath dotnet -ArgumentList "run --project FlinkDotNetAspire.AppHost.csproj --no-launch-profile --no-build -c Release" -RedirectStandardOutput $aspireLog -RedirectStandardError $aspireLog -PassThru
          $env:ASPIRE_APPHOST_PID = $process.Id
          Write-Host "Aspire AppHost started with PID $env:ASPIRE_APPHOST_PID"
          Write-Host "Waiting for Aspire AppHost to initialize..."
          Start-Sleep -Seconds 30
          Pop-Location


      # The AppHost binds Redis and Kafka to their default ports so the verifier
      # can use localhost addresses directly. Expose these connection strings to
      # later steps via environment variables.
      - name: Set Service URLs
        run: |
          Add-Content -Path $env:GITHUB_ENV -Value "DOTNET_REDIS_URL=localhost:6379"
          Add-Content -Path $env:GITHUB_ENV -Value "DOTNET_KAFKA_BOOTSTRAP_SERVERS=localhost:9092"

      - name: Health Check Loop
        env:
          DOTNET_ENVIRONMENT: "Development" # Helps Aspire resolve services if it has multiple modes
        run: |
          $maxAttempts = 10
          $delaySeconds = 15
          $verifierDll = "./FlinkDotNetAspire/IntegrationTestVerifier/bin/Release/net8.0/FlinkDotNet.IntegrationTestVerifier.dll"

          for ($attempt = 1; $attempt -le $maxAttempts; $attempt++) {
            echo "Health check attempt $attempt/$maxAttempts..."
            & dotnet $verifierDll --health-check
            if ($LASTEXITCODE -eq 0) {
              echo "Health check PASSED."
              break
            }
            echo "Health check FAILED. Waiting $delaySeconds seconds before retry..."
            Start-Sleep -Seconds $delaySeconds
            if ($attempt -eq $maxAttempts) {
              echo "Max health check attempts reached. Failing workflow."
              exit 1
            }
          }

      - name: Run Verification Tests
        env:
          # SIMULATOR_NUM_MESSAGES needs to be the same as used by the job simulator.
          SIMULATOR_NUM_MESSAGES: ${{ env.SIMULATOR_NUM_MESSAGES_CI }}
          DOTNET_ENVIRONMENT: "Development"
        run: |
          echo "Running verification tests with SIMULATOR_NUM_MESSAGES=${{ env.SIMULATOR_NUM_MESSAGES_CI }}..."
          Write-Host "DOTNET_REDIS_URL from env: $env:DOTNET_REDIS_URL"
          Write-Host "DOTNET_KAFKA_BOOTSTRAP_SERVERS from env: $env:DOTNET_KAFKA_BOOTSTRAP_SERVERS"
          $verifierDll = "./FlinkDotNetAspire/IntegrationTestVerifier/bin/Release/net8.0/FlinkDotNet.IntegrationTestVerifier.dll"
          & dotnet $verifierDll
          if ($LASTEXITCODE -ne 0) {
            echo "Verification tests FAILED."
            exit 1
          }
          echo "Verification tests PASSED."

      - name: Stop .NET Aspire Application (Best Effort)
        if: always()
        run: |
          echo "Attempting to stop .NET Aspire AppHost..."
          if ($env:ASPIRE_APPHOST_PID) {
            try {
              Stop-Process -Id $env:ASPIRE_APPHOST_PID -Force -ErrorAction Stop
            } catch {
              Write-Host "Failed to stop process $env:ASPIRE_APPHOST_PID : $_"
            }
          }
          # Fallback: stop any remaining dotnet processes running the AppHost.
          Get-Process dotnet | Where-Object { $_.CommandLine -like "*FlinkDotNetAspire.AppHost.csproj*" } | Stop-Process -Force -ErrorAction SilentlyContinue
          echo "Cleanup complete."
