name: Publish Integration Test Image

on:
  push:
    paths:
      - 'IntegrationTestImage/**'
      - 'workflows/publish-integration-test-image.yml'
  workflow_dispatch:

jobs:
  publish-image:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install .NET Aspire Workload
        run: dotnet workload install aspire
      - name: Build Docker Image
        run: docker build -t flink-dotnet-linux:latest -f IntegrationTestImage/Dockerfile .
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push Image
        run: |
          docker tag flink-dotnet-linux:latest ghcr.io/${{ github.repository_owner }}/flink-dotnet-linux:latest
          docker push ghcr.io/${{ github.repository_owner }}/flink-dotnet-linux:latest
