name: Publish Integration Test Image

on:
  workflow_dispatch:

jobs:
  publish-image:
    runs-on: windows-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Install .NET Aspire Workload
        run: dotnet workload install aspire
      - name: Build Docker Image
        run: dotnet publish IntegrationTestImage/IntegrationTestImage.csproj -p:PublishProfile=DockerDeploy
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Push Image
        run: |
          docker tag flink-dotnet-windows:latest ghcr.io/${{ github.repository_owner }}/flink-dotnet-windows:latest
          docker push ghcr.io/${{ github.repository_owner }}/flink-dotnet-windows:latest
