name: SonarCloud Analysis

on:
  push:
    branches:
      - main # Or your primary branch name
  pull_request:
    types: [synchronize]
    branches:
      - main # Or your primary branch name

concurrency:
  group: |
    ${{ github.workflow }}-${{ github.workflow_ref }}-${{
      github.event_name == 'pull_request' 
      && github.event.pull_request.number 
      || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest # Using windows-latest as per user's provided workflow
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # SonarScanner needs Java
          distribution: 'zulu'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarCloud analysis to correctly track changes

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache # Windows specific path for SonarQube/SonarCloud scanner cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner # Local path for the SonarScanner CLI
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner


      # Install .NET Aspire workload first
      - name: Install .NET Aspire Workload
        shell: pwsh
        run: dotnet workload install aspire

      # Then restore workloads for all solutions
      - name: Restore .NET Workloads for Solutions
        shell: pwsh
        run: |
          dotnet workload restore FlinkDotNet/FlinkDotNet.sln
          dotnet workload restore FlinkDotNetAspire/FlinkDotNetAspire.sln
          dotnet workload restore FlinkDotNet.WebUI/FlinkDotNet.WebUI.sln

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For PR decoration and SonarCloud <-> GitHub integration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your generated SonarCloud token
        shell: pwsh # Using PowerShell
        run: |
            function RunCommandWithWarningCheck($command, $description) {
              Write-Host "Running $description"
              $output = & $command 2>&1

              $output | ForEach-Object { Write-Host $_ }

              if ($LASTEXITCODE -ne 0) {
                Write-Host "[FAIL] $description failed with exit code $LASTEXITCODE"
                return -1
              }
              $warnings = $output | Where-Object { $_ -match "(?i)warning " }
              if ($warnings.Count -gt 0) {
                Write-Host "[WARN] Found warning(s) in ${description}:"
                $warnings | ForEach-Object { Write-Host "  $_" }
              } else {
                Write-Host "[OK] $description completed successfully with no warnings."
              }

              return $warnings.Count
            }

            # Begin SonarCloud analysis (without coverage paths yet)
            $beginCmd = { .\.sonar\scanner\dotnet-sonarscanner begin /k:"devstress_FLINK.NET" /o:"devstress" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.scanner.skipJreProvisioning=true /d:sonar.scanner.scanAll=false /d:sonar.coverage.exclusions="**/Program.cs,**/Migrations/**" }
            $exitBegin = RunCommandWithWarningCheck $beginCmd "Sonar begin"

            $exit1 = RunCommandWithWarningCheck { dotnet build FlinkDotNet/FlinkDotNet.sln } "Build FlinkDotNet"
            $exit2 = RunCommandWithWarningCheck { dotnet build FlinkDotNetAspire/FlinkDotNetAspire.sln } "Build FlinkDotNetAspire"
            $exit3 = RunCommandWithWarningCheck { dotnet build FlinkDotNet.WebUI/FlinkDotNet.WebUI.sln } "Build FlinkDotNet.WebUI"

            $totalWarnings = 0
            $buildFailed = $false
            $failedProcesses = @()
            
            $results = @(
              @{Name="Sonar begin"; Exit=$exitBegin},
              @{Name="Build FlinkDotNet"; Exit=$exit1},
              @{Name="Build FlinkDotNetAspire"; Exit=$exit2},
              @{Name="Build FlinkDotNet.WebUI"; Exit=$exit3}
            )
            
            foreach ($result in $results) {
              if ($result.Exit -lt 0) {
                $buildFailed = $true
                $failedProcesses += $result.Name
              } elseif ($result.Exit -gt 0) {
                $totalWarnings += $result.Exit
              }
            }

            if ($buildFailed) {
              if ($failedProcesses.Count -gt 0) {
                Write-Error "[ERROR] CI failed due to build errors in: $($failedProcesses -join ', ')"
              } else {
                Write-Error "[ERROR] CI failed due to build errors."
              }
            }

            if ($totalWarnings -gt 0) {
              Write-Error "[ERROR] Should be no warning, found warning(s)"
            } else {
              Write-Host "[OK] All builds passed with no warnings."
            }

      # Try to download test results and coverage from unit-tests workflow (if available)
      - name: Download test artifacts (if available)
        uses: actions/download-artifact@v4
        continue-on-error: true # Don't fail if artifacts aren't available yet
        with:
          name: dotnet-test-results
          path: ./FlinkDotNet/TestResults

      - name: Check for existing test artifacts and run tests if needed
        shell: pwsh
        run: |
          $artifactsAvailable = $false
          
          # Check if we have test artifacts from unit-tests workflow
          if (Test-Path "./FlinkDotNet/TestResults") {
            $openCoverFiles = Get-ChildItem -Path "./FlinkDotNet/TestResults" -Recurse -Filter "*.opencover.xml" -ErrorAction SilentlyContinue
            if ($openCoverFiles.Count -gt 0) {
              Write-Host "Found existing test artifacts from unit-tests workflow:"
              $openCoverFiles | ForEach-Object {
                Write-Host "  $($_.FullName) (Size: $($_.Length) bytes)"
              }
              $artifactsAvailable = $true
            }
          }
          
          if (-not $artifactsAvailable) {
            Write-Host "No test artifacts available from unit-tests workflow - running tests locally for coverage..."
            
            # Run tests with coverage collection for SonarCloud
            Push-Location FlinkDotNet
            dotnet test FlinkDotNet.sln --configuration Release --logger "trx" --results-directory "TestResults" --collect:"XPlat Code Coverage" --settings ../coverlet.runsettings
            Pop-Location
            
            # Convert coverage to OpenCover format for SonarCloud
            dotnet tool install --global dotnet-reportgenerator-globaltool --version 5.2.0 2>$null
            
            Get-ChildItem -Path "./FlinkDotNet/TestResults" -Recurse -Filter "coverage.cobertura.xml" | ForEach-Object {
              $coberturaFile = $_.FullName
              $targetDir = $_.DirectoryName
              Write-Host "Converting coverage file: $coberturaFile"
              
              # Convert to OpenCover format for SonarCloud
              $openCoverFile = Join-Path $targetDir "coverage.opencover.xml"
              Write-Host "Converting to OpenCover format: $openCoverFile"
              reportgenerator -reports:"$coberturaFile" -targetdir:"$targetDir" -reporttypes:"OpenCover" -verbosity:Info
            }
            
            Write-Host "Local test execution completed with coverage collection."
          }
          
          # Final verification of coverage files
          Write-Host "Final coverage files verification:"
          $finalOpenCoverFiles = Get-ChildItem -Path "./FlinkDotNet/TestResults" -Recurse -Filter "*.opencover.xml" -ErrorAction SilentlyContinue
          if ($finalOpenCoverFiles.Count -gt 0) {
            Write-Host "Coverage files ready for SonarCloud:"
            $finalOpenCoverFiles | ForEach-Object {
              Write-Host "  $($_.FullName) (Size: $($_.Length) bytes)"
            }
          } else {
            Write-Host "Warning: No OpenCover files found - SonarCloud will run without coverage data"
          }

      - name: Submit test coverage to SonarCloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For PR decoration and SonarCloud <-> GitHub integration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your generated SonarCloud token
        shell: pwsh # Using PowerShell
        run: |
            function RunCommandWithWarningCheck($command, $description) {
              Write-Host "Running $description"
              $output = & $command 2>&1

              $output | ForEach-Object { Write-Host $_ }

              if ($LASTEXITCODE -ne 0) {
                Write-Host "[FAIL] $description failed with exit code $LASTEXITCODE"
                return -1
              }
              $warnings = $output | Where-Object { $_ -match "(?i)warning " }
              if ($warnings.Count -gt 0) {
                Write-Host "[WARN] Found warning(s) in ${description}:"
                $warnings | ForEach-Object { Write-Host "  $_" }
              } else {
                Write-Host "[OK] $description completed successfully with no warnings."
              }

              return $warnings.Count
            }

            # Add coverage paths now that tests have been run
            Write-Host "Adding coverage paths and finalizing SonarCloud analysis..."
            
            # Check for coverage files
            $finalOpenCoverFiles = Get-ChildItem -Path "./FlinkDotNet/TestResults" -Recurse -Filter "*.opencover.xml" -ErrorAction SilentlyContinue
            if ($finalOpenCoverFiles.Count -gt 0) {
              Write-Host "Coverage files found for SonarCloud submission:"
              $finalOpenCoverFiles | ForEach-Object {
                Write-Host "  $($_.FullName) (Size: $($_.Length) bytes)"
              }
              
              # Set coverage paths and finalize SonarCloud analysis
              $endCmd = { .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.cs.opencover.reportsPaths="FlinkDotNet/TestResults/**/*.opencover.xml" }
            } else {
              Write-Host "Warning: No coverage files found - submitting analysis without coverage"
              $endCmd = { .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}" }
            }
            
            $exitEnd = RunCommandWithWarningCheck $endCmd "Sonar end with coverage"

            if ($exitEnd -ne 0) {
              Write-Error "[ERROR] SonarCloud submission failed with exit code $exitEnd"
            } else {
              Write-Host "[OK] SonarCloud analysis and coverage submitted successfully."
            }
