name: SonarCloud Analysis

on:
  push:
    branches:
      - main # Or your primary branch name
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest # Using windows-latest as per user's provided workflow
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # SonarScanner needs Java
          distribution: 'zulu'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Required for SonarCloud analysis to correctly track changes

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache # Windows specific path for SonarQube/SonarCloud scanner cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner # Local path for the SonarScanner CLI
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: powershell # Using PowerShell as per user's provided workflow
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      # New step to install .NET workloads
      - name: Install .NET Aspire Workload
        shell: powershell # Or bash, ensure consistency with other script steps if needed
        run: |
          dotnet workload restore FlinkDotNet/FlinkDotNet.sln
          dotnet workload restore FlinkDotNetAspire/FlinkDotNetAspire.sln
          dotnet workload restore FlinkDotNet.WebUI/FlinkDotNet.WebUI.sln

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For PR decoration and SonarCloud <-> GitHub integration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your generated SonarCloud token
        shell: powershell # Using PowerShell
        run: |
            function RunCommandWithWarningCheck($command, $description) {
              Write-Host "Running $description"
              $output = & $command 2>&1

              $output | ForEach-Object { Write-Host $_ }

              if ($LASTEXITCODE -ne 0) {
                Write-Host "[FAIL] $description failed"
                return -1
              }

              $warnings = $output | Where-Object { $_ -match "(?i)Warning:" }
              if ($warnings.Count -gt 0) {
                Write-Host "[WARN] Found $($warnings.Count) warning(s) in $description"
              } else {
                Write-Host "[OK] $description completed successfully with no warnings."
              }

              return $warnings.Count
            }

            $beginCmd = { .\.sonar\scanner\dotnet-sonarscanner begin /k:"devstress_FLINK.NET" /o:"devstress" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.scanner.skipJreProvisioning=true /d:sonar.scanner.scanAll=false }
            $exitBegin = RunCommandWithWarningCheck $beginCmd "Sonar begin"

            $exit1 = RunCommandWithWarningCheck { dotnet build FlinkDotNet/FlinkDotNet.sln } "Build FlinkDotNet"
            $exit2 = RunCommandWithWarningCheck { dotnet build FlinkDotNetAspire/FlinkDotNetAspire.sln } "Build FlinkDotNetAspire"
            $exit3 = RunCommandWithWarningCheck { dotnet build FlinkDotNet.WebUI/FlinkDotNet.WebUI.sln } "Build FlinkDotNet.WebUI"

            $endCmd = { .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}" }
            $exitEnd = RunCommandWithWarningCheck $endCmd "Sonar end"

            $totalWarnings = 0
            $buildFailed = $false
            foreach ($exit in @($exitBegin, $exit1, $exit2, $exit3, $exitEnd)) {
              if ($exit -lt 0) {
                $buildFailed = $true
              } elseif ($exit -gt 0) {
                $totalWarnings += $exit
              }
            }

            if ($buildFailed -or $exitEnd -ne 0) {
              Write-Error "[ERROR] CI failed due to build errors."
            }

            if ($totalWarnings -gt 0) {
              Write-Error "[ERROR] Should be no warning, found $totalWarnings warning(s)"
            } else {
              Write-Host "[OK] All builds passed with no warnings."
            }
