name: SonarCloud Analysis

on:
  workflow_run:
    workflows: ["Unit Tests"]
    types:
      - completed

concurrency:
  group: |
    ${{ github.workflow }}-${{ github.workflow_ref }}-${{
      github.event_name == 'pull_request' 
      && github.event.pull_request.number 
      || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    name: Build and Analyze
    runs-on: windows-latest # Using windows-latest as per user's provided workflow
    steps:
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # SonarScanner needs Java
          distribution: 'zulu'

      - name: Debug workflow run context
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow run status: ${{ github.event.workflow_run.status }}"
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow run head branch: ${{ github.event.workflow_run.head_branch }}"
          echo "Workflow run head SHA: ${{ github.event.workflow_run.head_sha }}"

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_sha }}
          fetch-depth: 0  # Required for SonarCloud analysis to correctly track changes

      - name: Set up .NET 8.0
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Cache SonarCloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache # Windows specific path for SonarQube/SonarCloud scanner cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarCloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: .\.sonar\scanner # Local path for the SonarScanner CLI
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarCloud scanner
        if: steps.cache-sonar-scanner.outputs.cache-hit != 'true'
        shell: pwsh
        run: |
          New-Item -Path .\.sonar\scanner -ItemType Directory
          dotnet tool update dotnet-sonarscanner --tool-path .\.sonar\scanner

      # Download coverage data from unit tests workflow if available
      - name: Download Coverage Data
        uses: actions/download-artifact@v4
        with:
          name: sonarcloud-coverage-data
          path: ./CoverageData
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          run-id: ${{ github.event.workflow_run.id || github.run_id }}
        continue-on-error: true

      # Install .NET Aspire workload first
      - name: Install .NET Aspire Workload
        shell: pwsh
        run: dotnet workload install aspire

      # Then restore workloads for all solutions
      - name: Restore .NET Workloads for Solutions
        shell: pwsh
        run: |
          dotnet workload restore FlinkDotNet/FlinkDotNet.sln
          dotnet workload restore FlinkDotNetAspire/FlinkDotNetAspire.sln
          dotnet workload restore FlinkDotNet.WebUI/FlinkDotNet.WebUI.sln

      - name: Build and analyze
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # For PR decoration and SonarCloud <-> GitHub integration
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}    # Your generated SonarCloud token
        shell: pwsh # Using PowerShell
        run: |
            function RunCommandWithWarningCheck($command, $description) {
              Write-Host "Running $description"
              $output = & $command 2>&1

              $output | ForEach-Object { Write-Host $_ }

              if ($LASTEXITCODE -ne 0) {
                Write-Host "[FAIL] $description failed with exit code $LASTEXITCODE"
                return -1
              }
              $warnings = $output | Where-Object { $_ -match "(?i)warning " }
              if ($warnings.Count -gt 0) {
                Write-Host "[WARN] Found warning(s) in ${description}:"
                $warnings | ForEach-Object { Write-Host "  $_" }
              } else {
                Write-Host "[OK] $description completed successfully with no warnings."
              }

              return $warnings.Count
            }

            $beginCmd = { .\.sonar\scanner\dotnet-sonarscanner begin /k:"devstress_FLINK.NET" /o:"devstress" /d:sonar.token="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.scanner.skipJreProvisioning=true /d:sonar.scanner.scanAll=false /d:sonar.cs.opencover.reportsPaths="./CoverageData/**/*.opencover.xml" /d:sonar.coverage.exclusions="**/Program.cs,**/Migrations/**" }
            $exitBegin = RunCommandWithWarningCheck $beginCmd "Sonar begin"

            $exit1 = RunCommandWithWarningCheck { dotnet build FlinkDotNet/FlinkDotNet.sln } "Build FlinkDotNet"
            $exit2 = RunCommandWithWarningCheck { dotnet build FlinkDotNetAspire/FlinkDotNetAspire.sln } "Build FlinkDotNetAspire"
            $exit3 = RunCommandWithWarningCheck { dotnet build FlinkDotNet.WebUI/FlinkDotNet.WebUI.sln } "Build FlinkDotNet.WebUI"

            # List coverage data from unit tests if downloaded
            Write-Host "Coverage data from unit tests workflow:"
            if (Test-Path "./CoverageData") {
              Get-ChildItem -Path "./CoverageData" -Recurse -Filter "*.xml" | ForEach-Object {
                Write-Host "  [FROM UNIT TESTS] $($_.FullName)"
              }
            } else {
              Write-Host "  No coverage data from unit tests workflow found"
            }
            
            # List all coverage files for debugging
            Write-Host "All coverage files found for SonarCloud:"
            Get-ChildItem -Path "./CoverageData" -Recurse -Filter "*.xml" -ErrorAction SilentlyContinue | ForEach-Object {
              Write-Host "  [UNIT TESTS] $($_.FullName)"
            }

            $endCmd = { .\.sonar\scanner\dotnet-sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}" }
            $exitEnd = RunCommandWithWarningCheck $endCmd "Sonar end"

            $totalWarnings = 0
            $buildFailed = $false
            $failedProcesses = @()
            
            $results = @(
              @{Name="Sonar begin"; Exit=$exitBegin},
              @{Name="Build FlinkDotNet"; Exit=$exit1},
              @{Name="Build FlinkDotNetAspire"; Exit=$exit2},
              @{Name="Build FlinkDotNet.WebUI"; Exit=$exit3},
              @{Name="Sonar end"; Exit=$exitEnd}
            )
            
            foreach ($result in $results) {
              if ($result.Exit -lt 0) {
                $buildFailed = $true
                $failedProcesses += $result.Name
              } elseif ($result.Exit -gt 0) {
                $totalWarnings += $result.Exit
              }
            }

            if ($buildFailed -or $exitEnd -ne 0) {
              if ($failedProcesses.Count -gt 0) {
                Write-Error "[ERROR] CI failed due to build errors in: $($failedProcesses -join ', ')"
              } else {
                Write-Error "[ERROR] CI failed due to build errors."
              }
            }

            if ($totalWarnings -gt 0) {
              Write-Error "[ERROR] Should be no warning, found warning(s)"
            } else {
              Write-Host "[OK] All builds passed with no warnings."
            }
